/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiPublicCommsEvolutionRouteImport } from './routes/api/public/comms/evolution'
import { Route as ApiPublicCommsInboundRouteImport } from './routes/api/public/comms/inbound'
import { Route as ApiPublicProductsSyncRouteImport } from './routes/api/public/products/sync'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCommsEvolutionRoute = ApiPublicCommsEvolutionRouteImport.update({
  id: '/api/public/comms/evolution',
  path: '/api/public/comms/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommsInboundRoute = ApiPublicCommsInboundRouteImport.update({
  id: '/api/public/comms/inbound',
  path: '/api/public/comms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSyncRoute = ApiPublicProductsSyncRouteImport.update({
  id: '/api/public/products/sync',
  path: '/api/public/products/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campaigns'
    | '/customers'
    | '/inbox'
    | '/inquiries'
    | '/orders'
    | '/products'
    | '/settings'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/campaigns'
    | '/customers'
    | '/inbox'
    | '/inquiries'
    | '/orders'
    | '/products'
    | '/settings'
    | '/'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/campaigns'
    | '/_authenticated/customers'
    | '/_authenticated/inbox'
    | '/_authenticated/inquiries'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCommsEvolutionRoute: typeof ApiPublicCommsEvolutionRoute
  ApiPublicCommsInboundRoute: typeof ApiPublicCommsInboundRoute
  ApiPublicProductsSyncRoute: typeof ApiPublicProductsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/comms/evolution': {
      id: '/api/public/comms/evolution'
      path: '/api/public/comms/evolution'
      fullPath: '/api/public/comms/evolution'
      preLoaderRoute: typeof ApiPublicCommsEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comms/inbound': {
      id: '/api/public/comms/inbound'
      path: '/api/public/comms/inbound'
      fullPath: '/api/public/comms/inbound'
      preLoaderRoute: typeof ApiPublicCommsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/sync': {
      id: '/api/public/products/sync'
      path: '/api/public/products/sync'
      fullPath: '/api/public/products/sync'
      preLoaderRoute: typeof ApiPublicProductsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCommsEvolutionRoute: ApiPublicCommsEvolutionRoute,
  ApiPublicCommsInboundRoute: ApiPublicCommsInboundRoute,
  ApiPublicProductsSyncRoute: ApiPublicProductsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
