/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAccountRecoveryRouteImport } from './routes/_authenticated/account-recovery'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedFieldRouteImport } from './routes/_authenticated/field'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedInquiriesRouteImport } from './routes/_authenticated/inquiries'
import { Route as AuthenticatedInviteRouteImport } from './routes/_authenticated/invite'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedRecruitmentRouteImport } from './routes/_authenticated/recruitment'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedWorkforceRouteImport } from './routes/_authenticated/workforce'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AuthenticatedPlatformIndexRouteImport } from './routes/_authenticated/platform/index'
import { Route as AuthenticatedPlatformAuditRouteImport } from './routes/_authenticated/platform/audit'
import { Route as AuthenticatedPlatformCompaniesRouteImport } from './routes/_authenticated/platform/companies'
import { Route as AuthenticatedPlatformPackagesRouteImport } from './routes/_authenticated/platform/packages'
import { Route as AuthenticatedPlatformReferralsRouteImport } from './routes/_authenticated/platform/referrals'
import { Route as ApiPublicCommsEvolutionRouteImport } from './routes/api/public/comms/evolution'
import { Route as ApiPublicCommsInboundRouteImport } from './routes/api/public/comms/inbound'
import { Route as ApiPublicProductsSyncRouteImport } from './routes/api/public/products/sync'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRecoveryRoute =
  AuthenticatedAccountRecoveryRouteImport.update({
    id: '/account-recovery',
    path: '/account-recovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFieldRoute = AuthenticatedFieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquiriesRoute = AuthenticatedInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInviteRoute = AuthenticatedInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecruitmentRoute =
  AuthenticatedRecruitmentRouteImport.update({
    id: '/recruitment',
    path: '/recruitment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkforceRoute = AuthenticatedWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformIndexRoute =
  AuthenticatedPlatformIndexRouteImport.update({
    id: '/platform/',
    path: '/platform/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformAuditRoute =
  AuthenticatedPlatformAuditRouteImport.update({
    id: '/platform/audit',
    path: '/platform/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformCompaniesRoute =
  AuthenticatedPlatformCompaniesRouteImport.update({
    id: '/platform/companies',
    path: '/platform/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformPackagesRoute =
  AuthenticatedPlatformPackagesRouteImport.update({
    id: '/platform/packages',
    path: '/platform/packages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformReferralsRoute =
  AuthenticatedPlatformReferralsRouteImport.update({
    id: '/platform/referrals',
    path: '/platform/referrals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCommsEvolutionRoute = ApiPublicCommsEvolutionRouteImport.update({
  id: '/api/public/comms/evolution',
  path: '/api/public/comms/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommsInboundRoute = ApiPublicCommsInboundRouteImport.update({
  id: '/api/public/comms/inbound',
  path: '/api/public/comms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSyncRoute = ApiPublicProductsSyncRouteImport.update({
  id: '/api/public/products/sync',
  path: '/api/public/products/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-recovery': typeof AuthenticatedAccountRecoveryRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/field': typeof AuthenticatedFieldRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/join/$token': typeof JoinTokenRoute
  '/r/$code': typeof RCodeRoute
  '/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/platform/companies': typeof AuthenticatedPlatformCompaniesRoute
  '/platform/packages': typeof AuthenticatedPlatformPackagesRoute
  '/platform/referrals': typeof AuthenticatedPlatformReferralsRoute
  '/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account-recovery': typeof AuthenticatedAccountRecoveryRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/field': typeof AuthenticatedFieldRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/inquiries': typeof AuthenticatedInquiriesRoute
  '/invite': typeof AuthenticatedInviteRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recruitment': typeof AuthenticatedRecruitmentRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/join/$token': typeof JoinTokenRoute
  '/r/$code': typeof RCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/platform/companies': typeof AuthenticatedPlatformCompaniesRoute
  '/platform/packages': typeof AuthenticatedPlatformPackagesRoute
  '/platform/referrals': typeof AuthenticatedPlatformReferralsRoute
  '/platform': typeof AuthenticatedPlatformIndexRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/account-recovery': typeof AuthenticatedAccountRecoveryRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/field': typeof AuthenticatedFieldRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/inquiries': typeof AuthenticatedInquiriesRoute
  '/_authenticated/invite': typeof AuthenticatedInviteRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/recruitment': typeof AuthenticatedRecruitmentRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/workforce': typeof AuthenticatedWorkforceRoute
  '/join/$token': typeof JoinTokenRoute
  '/r/$code': typeof RCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/platform/audit': typeof AuthenticatedPlatformAuditRoute
  '/_authenticated/platform/companies': typeof AuthenticatedPlatformCompaniesRoute
  '/_authenticated/platform/packages': typeof AuthenticatedPlatformPackagesRoute
  '/_authenticated/platform/referrals': typeof AuthenticatedPlatformReferralsRoute
  '/_authenticated/platform/': typeof AuthenticatedPlatformIndexRoute
  '/api/public/comms/evolution': typeof ApiPublicCommsEvolutionRoute
  '/api/public/comms/inbound': typeof ApiPublicCommsInboundRoute
  '/api/public/products/sync': typeof ApiPublicProductsSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/account-recovery'
    | '/campaigns'
    | '/collections'
    | '/command-center'
    | '/customers'
    | '/field'
    | '/inbox'
    | '/inquiries'
    | '/invite'
    | '/orders'
    | '/performance'
    | '/products'
    | '/recruitment'
    | '/settings'
    | '/targets'
    | '/workforce'
    | '/join/$token'
    | '/r/$code'
    | '/platform/audit'
    | '/platform/companies'
    | '/platform/packages'
    | '/platform/referrals'
    | '/platform/'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/account-recovery'
    | '/campaigns'
    | '/collections'
    | '/command-center'
    | '/customers'
    | '/field'
    | '/inbox'
    | '/inquiries'
    | '/invite'
    | '/orders'
    | '/performance'
    | '/products'
    | '/recruitment'
    | '/settings'
    | '/targets'
    | '/workforce'
    | '/join/$token'
    | '/r/$code'
    | '/'
    | '/platform/audit'
    | '/platform/companies'
    | '/platform/packages'
    | '/platform/referrals'
    | '/platform'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/account-recovery'
    | '/_authenticated/campaigns'
    | '/_authenticated/collections'
    | '/_authenticated/command-center'
    | '/_authenticated/customers'
    | '/_authenticated/field'
    | '/_authenticated/inbox'
    | '/_authenticated/inquiries'
    | '/_authenticated/invite'
    | '/_authenticated/orders'
    | '/_authenticated/performance'
    | '/_authenticated/products'
    | '/_authenticated/recruitment'
    | '/_authenticated/settings'
    | '/_authenticated/targets'
    | '/_authenticated/workforce'
    | '/join/$token'
    | '/r/$code'
    | '/_authenticated/'
    | '/_authenticated/platform/audit'
    | '/_authenticated/platform/companies'
    | '/_authenticated/platform/packages'
    | '/_authenticated/platform/referrals'
    | '/_authenticated/platform/'
    | '/api/public/comms/evolution'
    | '/api/public/comms/inbound'
    | '/api/public/products/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  JoinTokenRoute: typeof JoinTokenRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicCommsEvolutionRoute: typeof ApiPublicCommsEvolutionRoute
  ApiPublicCommsInboundRoute: typeof ApiPublicCommsInboundRoute
  ApiPublicProductsSyncRoute: typeof ApiPublicProductsSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account-recovery': {
      id: '/_authenticated/account-recovery'
      path: '/account-recovery'
      fullPath: '/account-recovery'
      preLoaderRoute: typeof AuthenticatedAccountRecoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/field': {
      id: '/_authenticated/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof AuthenticatedFieldRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries': {
      id: '/_authenticated/inquiries'
      path: '/inquiries'
      fullPath: '/inquiries'
      preLoaderRoute: typeof AuthenticatedInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite': {
      id: '/_authenticated/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof AuthenticatedInviteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruitment': {
      id: '/_authenticated/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AuthenticatedRecruitmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workforce': {
      id: '/_authenticated/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform/': {
      id: '/_authenticated/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof AuthenticatedPlatformIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/audit': {
      id: '/_authenticated/platform/audit'
      path: '/platform/audit'
      fullPath: '/platform/audit'
      preLoaderRoute: typeof AuthenticatedPlatformAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/companies': {
      id: '/_authenticated/platform/companies'
      path: '/platform/companies'
      fullPath: '/platform/companies'
      preLoaderRoute: typeof AuthenticatedPlatformCompaniesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/packages': {
      id: '/_authenticated/platform/packages'
      path: '/platform/packages'
      fullPath: '/platform/packages'
      preLoaderRoute: typeof AuthenticatedPlatformPackagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform/referrals': {
      id: '/_authenticated/platform/referrals'
      path: '/platform/referrals'
      fullPath: '/platform/referrals'
      preLoaderRoute: typeof AuthenticatedPlatformReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/comms/evolution': {
      id: '/api/public/comms/evolution'
      path: '/api/public/comms/evolution'
      fullPath: '/api/public/comms/evolution'
      preLoaderRoute: typeof ApiPublicCommsEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comms/inbound': {
      id: '/api/public/comms/inbound'
      path: '/api/public/comms/inbound'
      fullPath: '/api/public/comms/inbound'
      preLoaderRoute: typeof ApiPublicCommsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/sync': {
      id: '/api/public/products/sync'
      path: '/api/public/products/sync'
      fullPath: '/api/public/products/sync'
      preLoaderRoute: typeof ApiPublicProductsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRecoveryRoute: typeof AuthenticatedAccountRecoveryRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedFieldRoute: typeof AuthenticatedFieldRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedInquiriesRoute: typeof AuthenticatedInquiriesRoute
  AuthenticatedInviteRoute: typeof AuthenticatedInviteRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRecruitmentRoute: typeof AuthenticatedRecruitmentRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedWorkforceRoute: typeof AuthenticatedWorkforceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlatformAuditRoute: typeof AuthenticatedPlatformAuditRoute
  AuthenticatedPlatformCompaniesRoute: typeof AuthenticatedPlatformCompaniesRoute
  AuthenticatedPlatformPackagesRoute: typeof AuthenticatedPlatformPackagesRoute
  AuthenticatedPlatformReferralsRoute: typeof AuthenticatedPlatformReferralsRoute
  AuthenticatedPlatformIndexRoute: typeof AuthenticatedPlatformIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRecoveryRoute: AuthenticatedAccountRecoveryRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedFieldRoute: AuthenticatedFieldRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedInquiriesRoute: AuthenticatedInquiriesRoute,
  AuthenticatedInviteRoute: AuthenticatedInviteRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRecruitmentRoute: AuthenticatedRecruitmentRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedWorkforceRoute: AuthenticatedWorkforceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlatformAuditRoute: AuthenticatedPlatformAuditRoute,
  AuthenticatedPlatformCompaniesRoute: AuthenticatedPlatformCompaniesRoute,
  AuthenticatedPlatformPackagesRoute: AuthenticatedPlatformPackagesRoute,
  AuthenticatedPlatformReferralsRoute: AuthenticatedPlatformReferralsRoute,
  AuthenticatedPlatformIndexRoute: AuthenticatedPlatformIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  JoinTokenRoute: JoinTokenRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicCommsEvolutionRoute: ApiPublicCommsEvolutionRoute,
  ApiPublicCommsInboundRoute: ApiPublicCommsInboundRoute,
  ApiPublicProductsSyncRoute: ApiPublicProductsSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
